name: Send a Tweet to @StandardStruct (Follow Us)
on: 
  push:
    branches:
      - master
jobs:
  tweet-prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: log
        run: echo "::set-env name=POST_COMMIT_MESSAGE::$(git log --no-merges -1 --pretty=%B)" && echo '${{ env.POST_COMMIT_MESSAGE }}'
      - name: "Let's tweet about this"
        uses: cixo/ifttt-trigger@v0.3
        with:
          key: "${{ secrets.WEBHOOK_URL }}"
          event: "stand_struct_tweet_1"
          value1: "${{ env.POST_COMMIT_MESSAGE }}"
